# Generated by Django 5.2.12 on 2026-04-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='service_type',
        ),
    ]
