# Generated by Django 5.2.12 on 2026-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_remove_vendor_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
