# Generated by Django 5.2.12 on 2026-04-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_vendor_business_name_vendor_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
