# Generated by Django 5.2.12 on 2026-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_remove_vendor_created_at_remove_vendor_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
