# Generated by Django 5.2.12 on 2026-04-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_remove_service_business_name_remove_vendor_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventapp.login'),
            preserve_default=False,
        ),
    ]
